"general":
  "id": "cartpole"
  "seed": 0
  "repeat": 1
  "is_tensorboardX": false
  "sumo_home": "/home/ncarrara/sumo_binaries/bin"
  "workspace": "tmp"
  "logging":
    "version": 1
    "disable_existing_loggers": false
    "formatters":
      "standard":
        "format": "[%(name)s] %(levelname)s - %(message)s"
    "handlers":
      "default":
        "level": "WARNING"
        "formatter": "standard"
        "class": "logging.StreamHandler"
    "loggers":
      "":
        "handlers": ["default"]
        "level": "WARNING"
        "propagate": false
      "some.logger.you.want.to.enable.in.the.code":
        "handlers": ["default"]
        "level": "ERROR"
        "propagate": false

"envs_collection": "cartpole_gravity_collection"
"create_datasets":
  "n_episodes": 1000
"gan_config":
  "data_size_by_source_env": 2048
  "batch_size": "max"
  "stop":
    "max_epochs": 20000
    "testing_loss_treshold": 0.01
  "lambda_": 0
  "D_n_updates": 1
  "G_n_updates": 1
  "use_bce_tf_function": False
  "type": "classic" # "wasserstein"
  #  "lipchitz_method": "clipping",
  "z_size": 1 #5
  "D_hidden_layers": [16, 8]
  "G_hidden_layers": [16,8]
  "D_activation": "tanh"
  "G_activation": "tanh"
  "negative_sampling":
    "grid_search":
      - "use_fake_target_samples": False
        "use_sources_samples": True
        "minibatch_size": 4096
      - null
