"traffic_params":
  "factory_type": "grid"
  "flow_params":
    "connector_params":
      "action_params":
        "module": "sow45.world.environments.traffic.agents.connectors.action.exchange_change_phase"
        "class_name": "ExtendChangePhaseConnector"
        "params":
          "phases": ["GrGr","rGrG"]
          "tl_params":
            "green_min": 10
            "green_max": 60
            "yellow_max": 3
            "red_max": 2
      "obs_params":
        "module": "sow45.world.environments.traffic.agents.connectors.observation.mock_obs_connector"
        "class_name": "MockObservationConnector"
        "params": {}
      "reward_params":
        "module": "sow45.world.environments.traffic.agents.connectors.reward.mock_reward_connector"
        "class_name": "MockRewardConnector"
        "params": {}
    "simulator": "traci"
    "vehs_per_hour": 300
    "vehicles_params":
      "min_gap": 2.5
      "max_speed": 30
      "decel": 7.5
      "speed_mode": "right_of_way"
    "sim_params":
      "restart_instance": true
      "sim_step": 1
      "render": false
      "print_warnings": false
    "env_params":
      "horizon": 400
      "additional_params":
        "target_velocity": 50
        "switch_time": 3
        "num_observed": 2
        "discrete": false
        "tl_type": "actuated"
        "num_local_edges": 4
        "num_local_lights": 4
    "net_params":
      "additional_params":
        "speed_limit": 35
        "grid_array":
          "short_length": 300
          "inner_length": 300
          "long_length": 100
          "row_num": 1
          "col_num": 1
          "cars_left": 1
          "cars_right": 1
          "cars_top": 1
          "cars_bot": 1
        "horizontal_lanes": 1
        "vertical_lanes": 1
"ray":
  "init":
    "local_mode": false
    "log_to_driver": true
    "logging_level": "DEBUG"
  "run_experiments":
    "experiments":
      "apex.json":
        "run": "APEX"
        "stop":
          "training_iteration": 10
        "config":
          "lr":
            "grid_search": [0.01]
          "sample_batch_size": 100
          "train_batch_size": 32
          "log_level": "DEBUG"
          "num_workers": 7
          "num_gpus": 1
          "num_cpus_per_worker": 1
          "gamma": 0.99
          "model":
            "conv_filters": [[32,[1,8],1],[32,[1,4],1],[32,[1,2],1]]
            "fcnet_hiddens": [512,256]
          "horizon": null
    "search_alg": null
    "scheduler": null
    "with_server": false
    "server_port": 4321
    "verbose": 2
    "progress_reporter": null
    "resume": false
    "queue_trials": false
    "reuse_actors": false
    "trial_executor": null
    "raise_on_failed_trial": true
    "concurrent": true
"general":
  "id": "main"
  "seed": 0
  "is_tensorboardX": false
  "workspace": "tmp/main"
  "logging":
    "version": 1
    "disable_existing_loggers": false
    "formatters":
      "standard":
        "format": "[%(name)s] %(levelname)s - %(message)s"
    "handlers":
      "default":
        "level": "INFO"
        "formatter": "standard"
        "class": "logging.StreamHandler"
    "loggers":
      "":
        "handlers": ["default"]
        "level": "INFO"
        "propagate": false
      "some.logger.you.want.to.enable.in.the.code":
        "handlers": ["default"]
        "level": "ERROR"
        "propagate": false
        
      
    
  


