"factory_type": "grid"
"ray":
  "init":
    "local_mode": false
    "log_to_driver": true
    "logging_level": "DEBUG"
  "run_experiments":
    "experiments":
      "fixing_seed.yaml":
        "run": "DQN"
        "stop":
          "training_iteration": 5
        "config":
          "log_level": "DEBUG"
          "n_step": 3
          "num_gpus": 0
          "num_workers": 2
          "buffer_size": 100000
          "learning_starts": 5000
          "train_batch_size": 256
          "rollout_fragment_length": 50
          "target_network_update_freq": 5000
          "timesteps_per_iteration": 10000
          "evaluation_interval": 1
          "exploration_config": {"type": "PerWorkerEpsilonGreedy"}
          "worker_side_prioritization": true
          "min_iter_time_s": 30
          "model":
            "custom_model": "queue_obs_model"
          "horizon": null
          "env_config":
            "agents_params":
              "grid_search":
                - "module": "sow45.world.environments.traffic.agents.agent_factory"
                  "class_name": "OneTlAgentByIntersection"
                  "params":
                    "action_params":
                      "module": "sow45.world.environments.traffic.agents.connectors.action.exchange_change_phase"
                      "class_name": "ExtendChangePhaseConnector"
                      "params":
                        "phases": ["GrGr","yryr","rGrG","ryry"]
                        "tl_params":
                          "green_min": 10
                          "green_max": 60
                          "yellow_max": 3
                          "red_max": 2
                    "obs_params":
                      "module": "sow45.world.environments.traffic.agents.connectors.observation.queue_obs_connector"
                      "class_name": "QueueObservationConnector"
                      "params":
                        "num_history": 60
                    "reward_params":
                      "module": "sow45.world.environments.traffic.agents.connectors.reward.queue_reward_connector"
                      "class_name": "QueueRewardConnector"
                      "params":
                        "stop_speed": 0.3
                        "n": 100
                # - "module": "sow45.world.environments.traffic.agents.agent_factory"
                #   "class_name": "OneTlAgentByIntersection"
                #   "params":
                #     "action_params":
                #       "module": "sow45.world.environments.traffic.agents.connectors.action.exchange_change_phase"
                #       "class_name": "ExtendChangePhaseConnector"
                #       "params":
                #         "phases": ["GrGr","yryr","rGrG","ryry"]
                #         "tl_params":
                #           "green_min": 10
                #           "green_max": 60
                #           "yellow_max": 3
                #           "red_max": 2
                #     "obs_params":
                #       "module": "sow45.world.environments.traffic.agents.connectors.observation.tdtse"
                #       "class_name": "TDTSEConnector"
                #       "params":
                #         "tl_logic": ["GrGr","yryr","rGrG","ryry"]
                #         "obs_params":
                #           "num_history": 60
                #           "detector_position": [5, 100]
                #         "phase_channel": true
                #     "reward_params":
                #       "module": "sow45.world.environments.traffic.agents.connectors.reward.queue_reward_connector"
                #       "class_name": "QueueRewardConnector"
                #       "params":
                #         "stop_speed": 0.3
                #         "n": 100
            "detector_params":
              "positions": [-5, -100]
              "frequency": 100
            "simulator": "traci"
            "vehs_per_hour": 300
            "vehicles_params":
              "min_gap": 2.5
              "max_speed": 30
              "decel": 7.5
              "speed_mode": "right_of_way"
            "sim_params":
              "restart_instance": true
              "sim_step": 1
              "render": false
              "print_warnings": false
            "env_params":
              "warmup_steps": 1
              "horizon": 1000
              "additional_params":
                "target_velocity": 50
                "switch_time": 3
                "num_observed": 2
                "discrete": false
                "tl_type": "actuated"
                "num_local_edges": 4
                "num_local_lights": 4
            "net_params":
              "additional_params":
                "speed_limit": 35
                "grid_array":
                  "short_length": 300
                  "inner_length": 300
                  "long_length": 100
                  "row_num": 1
                  "col_num": 1
                  "cars_left": 1
                  "cars_right": 1
                  "cars_top": 1
                  "cars_bot": 1
                "horizontal_lanes": 1
                "vertical_lanes": 1

#    "search_alg": null
#    "scheduler": null
#    "with_server": false
#    "server_port": 4321
#    "verbose": 2
#    "progress_reporter": null
#    "resume": false
#    "queue_trials": true
#    "reuse_actors": false
#    "trial_executor": null
#    "raise_on_failed_trial": true
#    "concurrent": true
"general":
  "id": "main"
  "seed": 0
  "is_tensorboardX": false
  "workspace": "tmp/main"
  "logging":
    "version": 1
    "disable_existing_loggers": false
    "formatters":
      "standard":
        "format": "[%(name)s] %(levelname)s - %(message)s"
    "handlers":
      "default":
        "level": "INFO"
        "formatter": "standard"
        "class": "logging.StreamHandler"
    "loggers":
      "":
        "handlers": ["default"]
        "level": "INFO"
        "propagate": false
      "some.logger.you.want.to.enable.in.the.code":
        "handlers": ["default"]
        "level": "ERROR"
        "propagate": false
        
      
    
  


