"general":
  "id": "main_swap"

"envs_collection": "gw_swap"

"import_models":
  "address": "googlecloud"
  "local_workspace": "/home/ncarrara/work/rltl/rltl/main/data/main_swap"
  "remote_workspace": "/home/nicolas_carrara1u/work/rltl/rltl/main/data/main_swap"
