"general":
  "id": "main_debug"

"envs_collection": "gw_swap"

"import_models":
  "address": "googlecloud"
  "local_workspace": "/home/ncarrara/work/rltl/rltl/main/data/main_debug"
  "remote_workspace": "/home/nicolas_carrara1u/work/rltl/rltl/main/data/main_debug"

"create_datasets":
  "exploration":
    "type": "uniform"
    "n_samples": 100

"inferences":
  "repeat_bayesian_inferences": 2
  "fake_color_alpha": 0.05
  "n_repeat_forward": 2
  "exploration":
    "n_repeat": 2
    "type": "grid" # "random"
    "deltas": [ 0.5,0.5 ]
    "std": 0.0

"threshold_context_sigma":
  "repeat_bayesian_inferences": 2
  "exploration":
    "type": "uniform"
    "n_samples": 3

"visualize_classifiers":
  "repeat_sources": 2
  "deltas_sources": [ 0.4,0.4 ]
  "repeat_context": 2
  "deltas_context": [ 0.4,0.4 ]
  "repeat_bayesian_inference": 2

"learn_classifiers":
  "baselines":
    "feedforward":
      "dynamics":
        "hidden_layers": [ [ "Dense",5 ],[ "Dense",5 ] ]
        "stop":
          "max_epochs": 2
          "testing_loss_treshold": 0.05
          "training_loss_treshold": 0.05
    "full_bayesian":
      "dynamics":
        "hidden_layers": [ [ "DenseVariational",5 ],[ "DenseVariational",5 ] ]
        "stop":
          "max_epochs": 2
          "testing_loss_treshold": 0.05
          "training_loss_treshold": 0.05

"learn_gans":
  "interval_verbose_minibatch": 2
  "interval_save_models": 2
  "interval_inferences": 2
  "interval_save_model": 2
  "interval_eval_epoch": 2
  "buffer_size_by_source_env": 2
  "batch_size": 2

  "stop":
    "max_epochs": 5



